// The file contents for the current environment will overwrite these during build. 
// `.env.ts` is generated by the `npm run env` command
import env from './.env';

// The `window.env` object is loaded in the `index.html` file
const loadedEnv = window.env || {};

export const environment = {
  production: false,
  version: env.mifos_x.version,
  hash: env.mifos_x.hash,

  /** Tenant Info */
  fineractPlatformTenantId: loadedEnv.fineractPlatformTenantId || 'default',
  fineractPlatformTenantIds: loadedEnv.fineractPlatformTenantIds || 'default',

  /** Multiple API endpoints for dropdown selection */
  baseApiUrls:
    loadedEnv.fineractApiUrls ||
    'https://pwdz.aheadbanker.com,https://sand.aheadbanker.com,https://sandbox.mifos.community,https://demo.mifos.community,https://localhost:8443',

  /** Default API URL */
  baseApiUrl:
    loadedEnv.fineractApiUrl ||
    (loadedEnv.fineractApiUrls?.length > 0
      ? loadedEnv.fineractApiUrls.split(',')[0]
      : 'https://pwdz.aheadbanker.com'),

  /** Allow user to select server in login page */
  allowServerSwitch: 'true',

  /** API paths */
  apiProvider: loadedEnv.apiProvider || '/fineract-provider/api',
  apiVersion: loadedEnv.apiVersion || '/v1',

  serverUrl: '',

  /** Session / Auth Config */
  enableRememberMe: false,
  oauth: {
    enabled: loadedEnv.oauthServerEnabled || false,
    serverUrl: loadedEnv.oauthServerUrl || '',
    appId: loadedEnv.oauthAppId || ''
  },

  /** Warning Popup Config */
  warningDialog: {
    title: 'Warning',
    content:
      'This system is for authorized use only. Unauthorized access will result in possible legal action. By accessing this system, you acknowledge that you are authorized to do so and that all data stored and processed here is confidential.',
    buttonText: 'Close'
  },

  /** Localization */
  defaultLanguage: loadedEnv.defaultLanguage || 'en-US',
  supportedLanguages:
    loadedEnv.supportedLanguages ||
    'cs-CS,de-DE,en-US,es-MX,fr-FR,it-IT,ko-KO,lt-LT,lv-LV,ne-NE,pt-PT,sw-SW',

  /** UI Options */
  preloadClients: loadedEnv.preloadClients || true,
  displayTenantSelector: loadedEnv.displayTenantSelector || 'true',
  displayBackEndInfo: loadedEnv.displayBackEndInfo || 'true',

  /** Timing Configs */
  waitTimeForNotifications: loadedEnv.waitTimeForNotifications || 60,
  waitTimeForCOBCatchUp: loadedEnv.waitTimeForCOBCatchUp || 30,

  /** Session Timeout */
  session: {
    timeout: {
      idleTimeout: loadedEnv.sessionIdleTimeout || 300000 // 5 minutes
    }
  },

  httpCacheEnabled: loadedEnv.httpCacheEnabled || false,

  /** OIDC Auth (disabled) */
  OIDC: {
    oidcServerEnabled: window['env']?.['oidcServerEnabled'] || false,
    oidcBaseUrl: window['env']?.['oidcBaseUrl'] || '',
    oidcClientId: window['env']?.['oidcClientId'] || '',
    oidcApiUrl: window['env']?.['oidcApiUrl'] || '',
    oidcFrontUrl: window['env']?.['oidcFrontUrl'] || ''
  },

  /** ✅ Added missing properties to fix compiler errors */
  minPasswordLength: 12,
  defaultCharDelimiter: ',',
  interbankTransfers: false,

  /** ✅ Added vNext API fields required by Account Transfers service */
  vNextApiUrl:
    loadedEnv.vNextApiUrl || 'https://pwdz.aheadbanker.com/fineract-provider/api',
  vNextApiVersion: loadedEnv.vNextApiVersion || '/v1',
  vNextApiProvider: loadedEnv.vNextApiProvider || '/fineract-provider/api'
};

/** Construct full API URL */
environment.serverUrl = `${environment.baseApiUrl}${environment.apiProvider}${environment.apiVersion}`;
